version: '3'
services:
  nginx:
    image: quay.io/akiray03/nginx-fastcertificate
    # build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/conf:/usr/local/nginx/conf
      - ./docker/hook:/usr/local/nginx/hook
      - ./logs:/usr/local/nginx/logs
    links:
      - redis:redis
    depends_on:
      - redis

  redis:
    image: redis:3.2-alpine
    expose:
      - '6379'
